/// Flutter icons YakadirIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YakadirIcons
///      fonts:
///       - asset: fonts/YakadirIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YakadirIcons {
  YakadirIcons._();

  static const _kFontFam = 'YakadirIcons';
  static const String? _kFontPkg = null;

  static const IconData share = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
